name: pm
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  

  
  flutter:
    sdk: flutter
  flutter_firebase_chat_core: ^1.6.8
  flutter_localizations:
    sdk: flutter
  modal_progress_hud_nsn: ^0.5.1
  provider: ^6.1.2
  flutter_chat_types: ^3.6.2
  meta: '>=1.8.0 <2.0.0'
  faker: ^2.1.0
  file_picker: ^8.0.6
  firebase_storage: ^12.1.1
  flutter_chat_ui: ^1.6.14
  image_picker: ^1.1.2
  mime: ^1.0.5
  open_filex: ^4.4.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
